### ISSUE TITLE
8 tabs instead of 2

### ISSUE THREAD

**Issue by Saibamen** [dotnet/EntityFramework.Docs.pl-pl#10]
URL: https://docs.microsoft.com/pl-pl/ef/core/managing-schemas/migrations/?tabs=vs

Img: 
![image](https://user-images.githubusercontent.com/905878/100079534-0a939f80-2e45-11eb-8e12-e2286a50d7df.png)

Chrome 87.0.4280.66 (Windows)

**Comment by JasonCard** [comment]
Thank you for reporting this issue and I'm following up.

**Comment by JasonCard** [comment]
@Saibamen Thank you for reporting this issue, and it's now fixed.
