### ISSUE TITLE
Remove-Migration command description

### ISSUE THREAD

**Issue by programista25** [dotnet/EntityFramework.Docs.pl-pl#5]
It would be nice if you write how to remove migration if it is created with output parameter. I've tried Remove-Migration -o "Migrations" but got this:
Remove-Migration : Parameter cannot be processed because the parameter name 'o' is ambiguous. Possible matches include: -OutVariable -OutBuffer.
At line:1 char:18
Could you update the description for such case?

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migracje — EF Core](https://docs.microsoft.com/pl-pl/ef/core/managing-schemas/migrations/?tabs=vs#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/dotnet/EntityFramework.Docs.pl-pl/blob/live/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by srvbpigh** [comment]
Hello, @programista25
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/EntityFramework.Docs #2203](https://github.com/dotnet/EntityFramework.Docs/issues/2203) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @programista25, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/EntityFramework.Docs/issues/2203. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
